# Generated by Django 5.2.7 on 2025-11-04 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('education', models.JSONField(default=list)),
                ('experience', models.JSONField(default=list)),
                ('skills', models.JSONField(default=list)),
                ('projects', models.JSONField(default=list)),
                ('ai_enhanced_summary', models.TextField(blank=True)),
                ('ai_suggested_skills', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
