import html2pdf from 'html2pdf.js';

export const generateResumePDF = (resumeData) => {
  console.log('Generating PDF for:', resumeData);
  
  // Create the HTML content for PDF
  const element = document.createElement('div');
  element.innerHTML = `
    <div style="font-family: Arial, sans-serif; padding: 30px; line-height: 1.6;">
      <!-- Header -->
      <div style="text-align: center; margin-bottom: 30px; border-bottom: 2px solid #3498db; padding-bottom: 20px;">
        <h1 style="color: #2c3e50; margin: 0; font-size: 28px;">${resumeData.full_name || 'Your Name'}</h1>
        <p style="color: #7f8c8d; margin: 5px 0;">📧 ${resumeData.email || 'Email'}</p>
        <p style="color: #7f8c8d; margin: 5px 0;">📱 ${resumeData.phone || 'Phone'}</p>
        <p style="color: #7f8c8d; margin: 5px 0;">📍 ${resumeData.address || 'Address'}</p>
      </div>

      <!-- Summary -->
      <div style="margin-bottom: 20px;">
        <h2 style="color: #3498db; border-bottom: 1px solid #bdc3c7; padding-bottom: 5px;">PROFESSIONAL SUMMARY</h2>
        <p>${resumeData.summary || 'Experienced professional seeking new opportunities.'}</p>
      </div>

      <!-- Skills -->
      <div style="margin-bottom: 20px;">
        <h2 style="color: #3498db; border-bottom: 1px solid #bdc3c7; padding-bottom: 5px;">SKILLS</h2>
        <p>${resumeData.skills && resumeData.skills.length > 0 ? resumeData.skills.join(', ') : 'No skills listed'}</p>
      </div>

      <!-- Education -->
      ${resumeData.education && resumeData.education.length > 0 ? `
        <div style="margin-bottom: 20px;">
          <h2 style="color: #3498db; border-bottom: 1px solid #bdc3c7; padding-bottom: 5px;">EDUCATION</h2>
          ${resumeData.education.map(edu => `
            <div style="margin-bottom: 10px;">
              <strong>${edu.degree || 'Degree'}</strong><br>
              ${edu.school || 'School'} | ${edu.year || 'Year'}
              ${edu.grade ? ` | ${edu.grade}` : ''}
            </div>
          `).join('')}
        </div>
      ` : ''}

      <!-- Experience -->
      ${resumeData.experience && resumeData.experience.length > 0 ? `
        <div style="margin-bottom: 20px;">
          <h2 style="color: #3498db; border-bottom: 1px solid #bdc3c7; padding-bottom: 5px;">EXPERIENCE</h2>
          ${resumeData.experience.map(exp => `
            <div style="margin-bottom: 15px;">
              <strong>${exp.title || 'Position'}</strong><br>
              <em>${exp.company || 'Company'} | ${exp.years || 'Period'}</em><br>
              ${exp.description || 'Description of responsibilities and achievements.'}
            </div>
          `).join('')}
        </div>
      ` : ''}

      <!-- Footer -->
      <div style="text-align: center; margin-top: 30px; padding-top: 20px; border-top: 1px solid #bdc3c7; color: #7f8c8d;">
        <p>Generated by AI Resume Builder</p>
      </div>
    </div>
  `;

  // PDF options
  const options = {
    margin: 10,
    filename: `${resumeData.full_name || 'resume'}_${Date.now()}.pdf`,
    image: { type: 'jpeg', quality: 0.98 },
    html2canvas: { 
      scale: 2,
      useCORS: true
    },
    jsPDF: { 
      unit: 'mm', 
      format: 'a4', 
      orientation: 'portrait' 
    }
  };

  // Generate and download PDF
  html2pdf().set(options).from(element).save();
};